### ISSUE TITLE
Option to exclude XT-IDE BIOS

### ISSUE THREAD

**Issue by TzOk83** [csoren/nuxt-bios#1]
Most XT-IDE adapters, including Monotech's one, have the XUB BIOS onboard, so no point in having it included in the main BIOS.

**Comment by csoren** [comment]
Thank you, this is something that will be considered as an option in the future. This project currently provides complete flashable BIOS images for the Monotech NuXT v1. This platform (and indeed, the NuXT v2) includes the XT-IDE option ROM at address F000:0000, which is part of the main BIOS, and must therefore be included in the build.
